apiVersion: v1
kind: Service
metadata:
  labels:
    app: control-plane
  name: control-plane
spec:
  ports:
    - name: "5200"
      port: 5200
      targetPort: 5200
  selector:
    app: control-plane
status:
  loadBalancer: {}
