apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: control-plane-route
  namespace: featbit
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
    - host: featbit-control-plane.local
      http:
        paths:
          - path: '/'
            pathType: Prefix
            backend:
              service:
                name: control-plane
                port:
                  number: 5200